# server port config
server:
  port: 8282

## DB config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.133.150:54467/finaldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: groupware
    password: groupware

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: classpath:/noticeimgs/
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        '[format_sql]': true


jwt:
  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==

# Logging Level
logging:
  level:
    root: info
#
#    image-dir: /noticeimgs
#    image-url: